---
apiVersion: v1
kind: Pod
metadata:
  name: pod-with-empty-dir volumes
spec:
  containers:
    - name: alpine-container
      image: alpine
      args:
        - /bin/sh
        - -c
        - sleep 1d
      volumeMounts:
        - mountPath: /data
          name: data-volume
        - mountPath: /var/log
          name: logs-volume
  volumes:
    - name: data-volume
      emptyDir: {}
    - name: logs-volume
      emptyDir: {}

   