---
apiVersion: v1
kind: Pod
metadata:
  name: label-demo2
  labels:
    environment: qa
    team: infra-ops
    project: qt-elearn
spec: 
  containers: 
    - name: jenkins-container
      image: jenkins/jenkins
      ports:
        - containerPort: 8080
          protocol: TCP