---
apiVersion: v1
kind: Pod
metadata:
  name: label-demo3
  labels:
    environment: qa
    team: sys-ops
    project: qt-elearn
spec: 
  containers: 
    - name: mysql-container
      image: mysql:latest
      ports:
        - containerPort: 3306
          protocol: TCP
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: 'qtadmin@123'