---
apiVersion: v1
kind: Pod
metadata:
  name: http-probe
spec:
  conatiners:
    - name: http-server
      iamge: httpd:latest
      ports:
        - containerPort: 80
          protocol: TCP
      livenessProbe:
        httpGet:
          port: 80
          path: /
        initialDelaySeconds: 10
        periodSeconds: 5
        successThreshold: 1
        failureThreshold: 1